# Generated by Django 2.1.7 on 2019-03-01 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190224_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20)),
                ('purchase_date', models.DateTimeField()),
                ('confirmed_date', models.DateTimeField()),
                ('planned_delivery_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField()),
                ('delivered_to_novastar_date', models.DateTimeField()),
                ('item_status', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('shipped_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 11, 18, 42, 158046), verbose_name='date published'),
        ),
    ]
