# Generated by Django 2.1.7 on 2019-03-01 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190301_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 14, 13, 34, 101668), verbose_name='date published'),
        ),
    ]
