# Generated by Django 2.1.7 on 2019-03-01 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190301_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20)),
                ('purchase_date', models.DateTimeField()),
                ('confirmed_date', models.DateTimeField()),
                ('planned_delivery_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField()),
                ('delivered_to_novastar_date', models.DateTimeField()),
                ('item_status', models.CharField(max_length=50)),
                ('item', models.TextField()),
                ('order_quantity', models.IntegerField()),
                ('open_items', models.TextField()),
                ('op_item_quantity', models.IntegerField()),
                ('shipped_items', models.TextField()),
                ('sh_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 14, 26, 47, 421470), verbose_name='date published'),
        ),
    ]
