# Generated by Django 2.1.7 on 2019-03-06 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190301_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='confirmed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_to_novastar_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='planned_delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 11, 18, 7, 830491), verbose_name='date published'),
        ),
    ]
